#
# WO template tag aliases.
#
# Format:
#   <alias>=<JavaClassShortNameOrFqn>
#
# Examples:
#   str=WOString
#   my=org.example.components.MyComponent
#
localized=er.extensions.localization.ERXLocalizedString
else=er.extensions.components.conditionals.ERXElse
if=er.extensions.components.conditionals.ERXWOConditional
conditional=er.extensions.components.conditionals.ERXWOConditional
condition=er.extensions.components.conditionals.ERXWOConditional
foreach=com.webobjects.appserver._private.WORepetition
repeat=com.webobjects.appserver._private.WORepetition
repetition=com.webobjects.appserver._private.WORepetition
loop=com.webobjects.appserver._private.WORepetition
content=com.webobjects.appserver._private.WOComponentContent
componentContent=com.webobjects.appserver._private.WOComponentContent
str=com.webobjects.appserver._private.WOString
string=com.webobjects.appserver._private.WOString
switchComponent=com.webobjects.appserver._private.WOSwitchComponent
switch=com.webobjects.appserver._private.WOSwitchComponent
XMLNode=com.webobjects.appserver._private.WOXMLNode
nestedList=com.webobjects.appserver._private.WONestedList
param=com.webobjects.appserver._private.WOParam
applet=com.webobjects.appserver._private.WOApplet
quickTime=com.webobjects.appserver._private.WOQuickTime
commentString=com.webobjects.appserver._private.WOHTMLCommentString
comment=com.webobjects.appserver._private.WOHTMLCommentString
noContentElement=com.webobjects.appserver._private.WONoContentElement
noContent=com.webobjects.appserver._private.WONoContentElement
body=com.webobjects.appserver._private.WOBody
embeddedObject=com.webobjects.appserver._private.WOEmbeddedObject
embedded=com.webobjects.appserver._private.WOEmbeddedObject
frame=com.webobjects.appserver._private.WOFrame
image=com.webobjects.appserver._private.WOImage
img=com.webobjects.appserver._private.WOImage
form=com.webobjects.appserver._private.WOForm
javaScript=com.webobjects.appserver._private.WOJavaScript
VBScript=com.webobjects.appserver._private.WOVBScript
resourceURL=com.webobjects.appserver._private.WOResourceURL
genericElement=com.webobjects.appserver._private.WOGenericElement
element=com.webobjects.appserver._private.WOGenericElement
genericContainer=com.webobjects.appserver._private.WOGenericContainer
container=com.webobjects.appserver._private.WOGenericContainer
activeImage=com.webobjects.appserver._private.WOActiveImage
checkBox=com.webobjects.appserver._private.WOCheckBox
checkbox=com.webobjects.appserver._private.WOCheckBox
fileUpload=com.webobjects.appserver._private.WOFileUpload
upload=com.webobjects.appserver._private.WOFileUpload
hiddenField=com.webobjects.appserver._private.WOHiddenField
hidden=com.webobjects.appserver._private.WOHiddenField
imageButton=com.webobjects.appserver._private.WOImageButton
inputList=com.webobjects.appserver._private.WOInputList
browser=com.webobjects.appserver._private.WOBrowser
checkBoxList=com.webobjects.appserver._private.WOCheckBoxList
popUpButton=com.webobjects.appserver._private.WOPopUpButton
select=com.webobjects.appserver._private.WOPopUpButton
radioButtonList=com.webobjects.appserver._private.WORadioButtonList
passwordField=com.webobjects.appserver._private.WOPasswordField
password=com.webobjects.appserver._private.WOPasswordField
radioButton=com.webobjects.appserver._private.WORadioButton
radio=com.webobjects.appserver._private.WORadioButton
resetButton=com.webobjects.appserver._private.WOResetButton
reset=com.webobjects.appserver._private.WOResetButton
submitButton=com.webobjects.appserver._private.WOSubmitButton
submit=com.webobjects.appserver._private.WOSubmitButton
text=com.webobjects.appserver._private.WOText
textField=com.webobjects.appserver._private.WOTextField
textfield=com.webobjects.appserver._private.WOTextField
search=com.webobjects.appserver._private.WOSearchField
searchfield=com.webobjects.appserver._private.WOSearchField
hyperlink=com.webobjects.appserver._private.WOHyperlink
link=com.webobjects.appserver._private.WOHyperlink
actionURL=com.webobjects.appserver._private.WOActionURL
