#
# WO template tag aliases.
#
# Format:
#   <alias>=<JavaClassShortNameOrFqn>
#
# Examples:
#   str=WOString
#   my=org.example.components.MyComponent
#
localized=ERXLocalizedString
else=ERXElse
if=ERXWOConditional
conditional=ERXWOConditional
condition=ERXWOConditional
foreach=WORepetition
repeat=WORepetition
repetition=WORepetition
loop=WORepetition
content=WOComponentContent
componentContent=WOComponentContent
str=WOString
string=WOString
switchComponent=WOSwitchComponent
switch=WOSwitchComponent
XMLNode=WOXMLNode
nestedList=WONestedList
param=WOParam
applet=WOApplet
quickTime=WOQuickTime
commentString=WOHTMLCommentString
comment=WOHTMLCommentString
noContentElement=WONoContentElement
noContent=WONoContentElement
body=WOBody
embeddedObject=WOEmbeddedObject
embedded=WOEmbeddedObject
frame=WOFrame
image=WOImage
img=WOImage
form=WOForm
javaScript=WOJavaScript
VBScript=WOVBScript
resourceURL=WOResourceURL
genericElement=WOGenericElement
element=WOGenericElement
genericContainer=WOGenericContainer
container=WOGenericContainer
activeImage=WOActiveImage
checkBox=WOCheckBox
checkbox=WOCheckBox
fileUpload=WOFileUpload
upload=WOFileUpload
hiddenField=WOHiddenField
hidden=WOHiddenField
imageButton=WOImageButton
inputList=WOInputList
browser=WOBrowser
checkBoxList=WOCheckBoxList
popUpButton=WOPopUpButton
select=WOPopUpButton
radioButtonList=WORadioButtonList
passwordField=WOPasswordField
password=WOPasswordField
radioButton=WORadioButton
radio=WORadioButton
resetButton=WOResetButton
reset=WOResetButton
submitButton=WOSubmitButton
submit=WOSubmitButton
text=WOText
textField=WOTextField
textfield=WOTextField
search=WOSearchField
searchfield=WOSearchField
hyperlink=WOHyperlink
link=WOHyperlink
actionURL=WOActionURL
